const x = () => {
  try {
    console.log(111111)
    console.log(dsgfsa)
    console.log(222222)
  } catch (err) {
    console.log(err)
  }
}

x()